node {
  name: "tf.Const"
  op: "Const"
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 2
          }
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        int_val: 3
      }
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.RandomUniform"
  op: "RandomUniform"
  input: "tf.Const"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 3
          }
          dim {
            size: 3
          }
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "seed"
    value {
      i: 0
    }
  }
  attr {
    key: "seed2"
    value {
      i: 0
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.Const1"
  op: "Const"
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 2
          }
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        int_val: 3
      }
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.RandomUniform1"
  op: "RandomUniform"
  input: "tf.Const1"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 3
          }
          dim {
            size: 3
          }
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "seed"
    value {
      i: 0
    }
  }
  attr {
    key: "seed2"
    value {
      i: 0
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.Complex"
  op: "Complex"
  input: "tf.RandomUniform"
  input: "tf.RandomUniform1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tout"
    value {
      type: DT_COMPLEX64
    }
  }
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 3
          }
          dim {
            size: 3
          }
        }
      }
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.Const2"
  op: "Const"
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 2
          }
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        int_val: 3
      }
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.RandomUniform2"
  op: "RandomUniform"
  input: "tf.Const2"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 3
          }
          dim {
            size: 3
          }
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "seed"
    value {
      i: 0
    }
  }
  attr {
    key: "seed2"
    value {
      i: 0
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.Const3"
  op: "Const"
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 2
          }
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        int_val: 3
      }
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.RandomUniform3"
  op: "RandomUniform"
  input: "tf.Const3"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 3
          }
          dim {
            size: 3
          }
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "seed"
    value {
      i: 0
    }
  }
  attr {
    key: "seed2"
    value {
      i: 0
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.Complex1"
  op: "Complex"
  input: "tf.RandomUniform2"
  input: "tf.RandomUniform3"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tout"
    value {
      type: DT_COMPLEX64
    }
  }
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 3
          }
          dim {
            size: 3
          }
        }
      }
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.Const4"
  op: "Const"
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 2
          }
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        int_val: 3
      }
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.RandomUniform4"
  op: "RandomUniform"
  input: "tf.Const4"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 3
          }
          dim {
            size: 3
          }
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "seed"
    value {
      i: 0
    }
  }
  attr {
    key: "seed2"
    value {
      i: 0
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.Const5"
  op: "Const"
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 2
          }
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        int_val: 3
      }
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.RandomUniform5"
  op: "RandomUniform"
  input: "tf.Const5"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 3
          }
          dim {
            size: 3
          }
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "seed"
    value {
      i: 0
    }
  }
  attr {
    key: "seed2"
    value {
      i: 0
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.Complex2"
  op: "Complex"
  input: "tf.RandomUniform4"
  input: "tf.RandomUniform5"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tout"
    value {
      type: DT_COMPLEX64
    }
  }
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 3
          }
          dim {
            size: 3
          }
        }
      }
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.Identity"
  op: "Identity"
  input: "tf.Complex2"
  attr {
    key: "T"
    value {
      type: DT_COMPLEX64
    }
  }
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 3
          }
          dim {
            size: 3
          }
        }
      }
    }
  }
  experimental_debug_info {
  }
}
node {
  name: "tf.PartitionedCall"
  op: "PartitionedCall"
  input: "tf.Complex"
  input: "tf.Complex1"
  input: "tf.Complex2"
  attr {
    key: "Tin"
    value {
      list {
        type: DT_COMPLEX64
        type: DT_COMPLEX64
        type: DT_COMPLEX64
      }
    }
  }
  attr {
    key: "Tout"
    value {
      list {
        type: DT_COMPLEX64
      }
    }
  }
  attr {
    key: "_collective_manager_ids"
    value {
      list {
      }
    }
  }
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 3
          }
          dim {
            size: 3
          }
        }
      }
    }
  }
  attr {
    key: "_read_only_resource_inputs"
    value {
      list {
      }
    }
  }
  attr {
    key: "config"
    value {
      s: ""
    }
  }
  attr {
    key: "config_proto"
    value {
      s: "\n\007\n\003CPU\020\001\n\007\n\003GPU\020\0002\002J\0008\001\202\001\000"
    }
  }
  attr {
    key: "executor_type"
    value {
      s: ""
    }
  }
  attr {
    key: "f"
    value {
      func {
        name: "__inference_cgemm_direct_390"
      }
    }
  }
  experimental_debug_info {
  }
}
library {
  function {
    signature {
      name: "__inference_cgemm_direct_390"
      input_arg {
        name: "inference_cgemm_direct_390"
        type: DT_COMPLEX64
      }
      input_arg {
        name: "inference_cgemm_direct_3901"
        type: DT_COMPLEX64
      }
      input_arg {
        name: "inference_cgemm_direct_3902"
        type: DT_COMPLEX64
      }
      output_arg {
        name: "inference_cgemm_direct_3903"
        type: DT_COMPLEX64
      }
    }
    node_def {
      name: "tf.Imag"
      op: "Imag"
      input: "inference_cgemm_direct_390"
      attr {
        key: "T"
        value {
          type: DT_COMPLEX64
        }
      }
      attr {
        key: "Tout"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.Real"
      op: "Real"
      input: "inference_cgemm_direct_390"
      attr {
        key: "T"
        value {
          type: DT_COMPLEX64
        }
      }
      attr {
        key: "Tout"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.Imag1"
      op: "Imag"
      input: "inference_cgemm_direct_3901"
      attr {
        key: "T"
        value {
          type: DT_COMPLEX64
        }
      }
      attr {
        key: "Tout"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.MatMul"
      op: "MatMul"
      input: "tf.Imag:output:0"
      input: "tf.Imag1:output:0"
      attr {
        key: "T"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      attr {
        key: "transpose_a"
        value {
          b: false
        }
      }
      attr {
        key: "transpose_b"
        value {
          b: false
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.MatMul1"
      op: "MatMul"
      input: "tf.Real:output:0"
      input: "tf.Imag1:output:0"
      attr {
        key: "T"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      attr {
        key: "transpose_a"
        value {
          b: false
        }
      }
      attr {
        key: "transpose_b"
        value {
          b: false
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.Real1"
      op: "Real"
      input: "inference_cgemm_direct_3901"
      attr {
        key: "T"
        value {
          type: DT_COMPLEX64
        }
      }
      attr {
        key: "Tout"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.MatMul2"
      op: "MatMul"
      input: "tf.Real:output:0"
      input: "tf.Real1:output:0"
      attr {
        key: "T"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      attr {
        key: "transpose_a"
        value {
          b: false
        }
      }
      attr {
        key: "transpose_b"
        value {
          b: false
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.Sub"
      op: "Sub"
      input: "tf.MatMul2:product:0"
      input: "tf.MatMul:product:0"
      attr {
        key: "T"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.MatMul3"
      op: "MatMul"
      input: "tf.Imag:output:0"
      input: "tf.Real1:output:0"
      attr {
        key: "T"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      attr {
        key: "transpose_a"
        value {
          b: false
        }
      }
      attr {
        key: "transpose_b"
        value {
          b: false
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.AddV2"
      op: "AddV2"
      input: "tf.MatMul1:product:0"
      input: "tf.MatMul3:product:0"
      attr {
        key: "T"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.Imag2"
      op: "Imag"
      input: "inference_cgemm_direct_3902"
      attr {
        key: "T"
        value {
          type: DT_COMPLEX64
        }
      }
      attr {
        key: "Tout"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.AddV21"
      op: "AddV2"
      input: "tf.AddV2:z:0"
      input: "tf.Imag2:output:0"
      attr {
        key: "T"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.Real2"
      op: "Real"
      input: "inference_cgemm_direct_3902"
      attr {
        key: "T"
        value {
          type: DT_COMPLEX64
        }
      }
      attr {
        key: "Tout"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.AddV22"
      op: "AddV2"
      input: "tf.Sub:z:0"
      input: "tf.Real2:output:0"
      attr {
        key: "T"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.Complex"
      op: "Complex"
      input: "tf.AddV22:z:0"
      input: "tf.AddV21:z:0"
      attr {
        key: "T"
        value {
          type: DT_FLOAT
        }
      }
      attr {
        key: "Tout"
        value {
          type: DT_COMPLEX64
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      experimental_debug_info {
      }
    }
    node_def {
      name: "tf.Identity"
      op: "Identity"
      input: "tf.Complex:out:0"
      attr {
        key: "T"
        value {
          type: DT_COMPLEX64
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              dim {
                size: 3
              }
              dim {
                size: 3
              }
            }
          }
        }
      }
      experimental_debug_info {
      }
    }
    ret {
      key: "inference_cgemm_direct_3903"
      value: "tf.Identity:output:0"
    }
    attr {
      key: "_construction_context"
      value {
        s: "kEagerRuntime"
      }
    }
    arg_attr {
      key: 0
      value {
        attr {
          key: "_output_shapes"
          value {
            list {
              shape {
                dim {
                  size: 3
                }
                dim {
                  size: 3
                }
              }
            }
          }
        }
        attr {
          key: "_user_specified_name"
          value {
            s: "A"
          }
        }
      }
    }
    arg_attr {
      key: 1
      value {
        attr {
          key: "_output_shapes"
          value {
            list {
              shape {
                dim {
                  size: 3
                }
                dim {
                  size: 3
                }
              }
            }
          }
        }
        attr {
          key: "_user_specified_name"
          value {
            s: "B"
          }
        }
      }
    }
    arg_attr {
      key: 2
      value {
        attr {
          key: "_output_shapes"
          value {
            list {
              shape {
                dim {
                  size: 3
                }
                dim {
                  size: 3
                }
              }
            }
          }
        }
        attr {
          key: "_user_specified_name"
          value {
            s: "C"
          }
        }
      }
    }
  }
}
versions {
  producer: 987
  min_consumer: 12
}
